-- MySQL Script generated by MySQL Workbench
-- 11/18/15 12:46:25
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema IGUN
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IGUN` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `IGUN` ;

-- -----------------------------------------------------
-- Table `IGUN`.`Faction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IGUN`.`Faction` ;

CREATE TABLE IF NOT EXISTS `IGUN`.`Faction` (
  `FactionId` INT NOT NULL,
  `FactionName` VARCHAR(45) NULL,
  `UnMember` TINYINT(1) NULL,
  PRIMARY KEY (`FactionId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IGUN`.`Race`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IGUN`.`Race` ;

CREATE TABLE IF NOT EXISTS `IGUN`.`Race` (
  `RaceId` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(1000) NULL,
  `Species` VARCHAR(45) NULL,
  `GalPop` INT NULL,
  `Homeworld` VARCHAR(45) NULL,
  `Language` VARCHAR(45) NULL,
  `leader` VARCHAR(45) NULL,
  `FactionId` INT NULL,
  PRIMARY KEY (`RaceId`),
  INDEX `fk_Race_Faction1_idx` (`FactionId` ASC),
  CONSTRAINT `fk_Race_Faction1`
    FOREIGN KEY (`FactionId`)
    REFERENCES `IGUN`.`Faction` (`FactionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IGUN`.`Sov`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IGUN`.`Sov` ;

CREATE TABLE IF NOT EXISTS `IGUN`.`Sov` (
  `SovId` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `RaceId` INT NULL,
  PRIMARY KEY (`SovId`),
  INDEX `fk_Sov_Race1_idx` (`RaceId` ASC),
  CONSTRAINT `fk_Sov_Race1`
    FOREIGN KEY (`RaceId`)
    REFERENCES `IGUN`.`Race` (`RaceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IGUN`.`StarSys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IGUN`.`StarSys` ;

CREATE TABLE IF NOT EXISTS `IGUN`.`StarSys` (
  `StarSysId` INT NOT NULL,
  `PlanetNum` VARCHAR(45) NULL,
  `Resources` VARCHAR(45) NULL,
  `SovId` INT NULL,
  `Population` INT NULL,
  `Diameter` INT NULL,
  PRIMARY KEY (`StarSysId`),
  INDEX `fk_StarSys_Sov1_idx` (`SovId` ASC),
  CONSTRAINT `fk_StarSys_Sov1`
    FOREIGN KEY (`SovId`)
    REFERENCES `IGUN`.`Sov` (`SovId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IGUN`.`Planet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IGUN`.`Planet` ;

CREATE TABLE IF NOT EXISTS `IGUN`.`Planet` (
  `PlanetId` INT NOT NULL,
  `Size` INT NULL,
  `Density` INT NULL,
  `Mass` INT NULL,
  `Name` VARCHAR(45) NULL,
  `Type` VARCHAR(45) NULL,
  `Atmosphere` VARCHAR(45) NULL,
  `Gravity` DOUBLE NULL,
  `Colonized` TINYINT(1) NULL,
  `LocLanguage` VARCHAR(45) NULL,
  `population` INT NULL,
  `StarSysId` INT NOT NULL,
  PRIMARY KEY (`PlanetId`),
  INDEX `fk_Planet_StarSys1_idx` (`StarSysId` ASC),
  CONSTRAINT `fk_Planet_StarSys1`
    FOREIGN KEY (`StarSysId`)
    REFERENCES `IGUN`.`StarSys` (`StarSysId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IGUN`.`Trade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IGUN`.`Trade` ;

CREATE TABLE IF NOT EXISTS `IGUN`.`Trade` (
  `TradeId` INT NOT NULL,
  `TradeProfit` VARCHAR(45) NULL,
  `RaceId` INT NOT NULL,
  PRIMARY KEY (`TradeId`),
  INDEX `fk_Trade_Race1_idx` (`RaceId` ASC),
  CONSTRAINT `fk_Trade_Race1`
    FOREIGN KEY (`RaceId`)
    REFERENCES `IGUN`.`Race` (`RaceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IGUN`.`Moon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IGUN`.`Moon` ;

CREATE TABLE IF NOT EXISTS `IGUN`.`Moon` (
  `MoonId` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Size` INT NULL,
  `Density` VARCHAR(45) NULL,
  `Mass` VARCHAR(45) NULL,
  `Type` ENUM('Terrestrial', 'Gas', 'Molten', 'Frozen', 'Desert', 'Oceanic', 'Storm') NULL,
  `AtmoMakeUp` VARCHAR(45) NULL,
  `Gravity` VARCHAR(45) NULL,
  `Inhabit` ENUM('Y','N') NULL,
  `Population` VARCHAR(45) NULL,
  `PlanetId` INT NOT NULL,
  PRIMARY KEY (`MoonId`),
  INDEX `fk_Moon_Planet1_idx` (`PlanetId` ASC),
  CONSTRAINT `fk_Moon_Planet1`
    FOREIGN KEY (`PlanetId`)
    REFERENCES `IGUN`.`Planet` (`PlanetId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IGUN`.`Military`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IGUN`.`Military` ;

CREATE TABLE IF NOT EXISTS `IGUN`.`Military` (
  `MilitaryId` INT NOT NULL,
  `FleetSize` INT NULL,
  `GroundForceSize` INT NULL,
  `RaceId` INT NOT NULL,
  PRIMARY KEY (`MilitaryId`),
  INDEX `fk_Military_Race1_idx` (`RaceId` ASC),
  CONSTRAINT `fk_Military_Race1`
    FOREIGN KEY (`RaceId`)
    REFERENCES `IGUN`.`Race` (`RaceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IGUN`.`MilCom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IGUN`.`MilCom` ;

CREATE TABLE IF NOT EXISTS `IGUN`.`MilCom` (
  `MilComId` INT NOT NULL,
  `ComFirstName` VARCHAR(45) NULL,
  `ComLastName` VARCHAR(45) NULL,
  `MilitaryId` INT NULL,
  PRIMARY KEY (`MilComId`),
  INDEX `fk_MilCom_Military1_idx` (`MilitaryId` ASC),
  CONSTRAINT `fk_MilCom_Military1`
    FOREIGN KEY (`MilitaryId`)
    REFERENCES `IGUN`.`Military` (`MilitaryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IGUN`.`MilFleet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IGUN`.`MilFleet` ;

CREATE TABLE IF NOT EXISTS `IGUN`.`MilFleet` (
  `MilFleetId` INT NOT NULL,
  `FleetName` VARCHAR(45) NULL,
  `NumShips` INT NULL,
  `NumPersonnel` INT NULL,
  `MilitaryId` INT NOT NULL,
  PRIMARY KEY (`MilFleetId`),
  INDEX `fk_MilFleet_Military1_idx` (`MilitaryId` ASC),
  CONSTRAINT `fk_MilFleet_Military1`
    FOREIGN KEY (`MilitaryId`)
    REFERENCES `IGUN`.`Military` (`MilitaryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IGUN`.`FlShips`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IGUN`.`FlShips` ;

CREATE TABLE IF NOT EXISTS `IGUN`.`FlShips` (
  `FlShipsId` INT NOT NULL,
`VehicleId` INT NOT NULL,
  `ShipName` VARCHAR(45) NULL,
  `Classification` VARCHAR(45) NULL,
  `Tier` ENUM('Frigate','Destroyer','Cruiser','Battleship','Carrier','Dreadnaught') NULL,
  `Size` VARCHAR(45) NULL,
  `Armament` VARCHAR(45) NULL,
  PRIMARY KEY (`FlShipsId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IGUN`.`Flcraft`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IGUN`.`Flcraft` ;

CREATE TABLE IF NOT EXISTS `IGUN`.`Flcraft` (
  `FlcraftId` INT NOT NULL,
`VehicleId` INT NOT NULL,
  `Type` ENUM('Fighters','Shuttles','Bombers') NULL,
  `Size` INT NULL,
  `Armament` VARCHAR(45) NULL,
  PRIMARY KEY (`FlcraftId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IGUN`.`Flground`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IGUN`.`Flground` ;

CREATE TABLE IF NOT EXISTS `IGUN`.`Flground` (
  `FlgroundId` INT NOT NULL,
`VehicleId` INT NOT NULL,
  `Structure` VARCHAR(45) NULL,
  `MainWeapon` VARCHAR(45) NULL,
  PRIMARY KEY (`FlgroundId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IGUN`.`SpaceStation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IGUN`.`SpaceStation` ;

CREATE TABLE IF NOT EXISTS `IGUN`.`SpaceStation` (
  `SpaceStationId` INT NOT NULL,
  `Use` ENUM('Civ','Mil') NULL,
  `Population` INT NULL,
  `ShipCap` INT NULL,
  `FlightCraftCap` INT NULL,
  `IndustrialCap` ENUM('Y','N') NULL,
  `RaceId` INT NOT NULL,
  PRIMARY KEY (`SpaceStationId`),
  INDEX `fk_SpaceStation_Race1_idx` (`RaceId` ASC),
  CONSTRAINT `fk_SpaceStation_Race1`
    FOREIGN KEY (`RaceId`)
    REFERENCES `IGUN`.`Race` (`RaceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IGUN`.`FacConditions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IGUN`.`FacConditions` ;

CREATE TABLE IF NOT EXISTS `IGUN`.`FacConditions` (
  `ConditionsId` INT NOT NULL,
  `FactionId` INT NULL,
  `Rule` VARCHAR(1000) NULL,
  PRIMARY KEY (`ConditionsId`),
  INDEX `fk_FacConditions_Faction_idx` (`FactionId` ASC),
  CONSTRAINT `fk_FacConditions_Faction`
    FOREIGN KEY (`FactionId`)
    REFERENCES `IGUN`.`Faction` (`FactionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IGUN`.`Admiral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IGUN`.`Admiral` ;

CREATE TABLE IF NOT EXISTS `IGUN`.`Admiral` (
  `AdmiralId` INT NOT NULL,
  `AdFirstname` VARCHAR(45) NULL,
  `AdLastName` VARCHAR(45) NULL,
  `MilFleetId` INT NOT NULL,
  PRIMARY KEY (`AdmiralId`),
  INDEX `fk_Admiral_MilFleet1_idx` (`MilFleetId` ASC),
  CONSTRAINT `fk_Admiral_MilFleet1`
    FOREIGN KEY (`MilFleetId`)
    REFERENCES `IGUN`.`MilFleet` (`MilFleetId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IGUN`.`Captain`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IGUN`.`Captain` ;

CREATE TABLE IF NOT EXISTS `IGUN`.`Captain` (
  `CaptainId` INT NOT NULL,
  `CapFirstName` VARCHAR(45) NULL,
  `CapLastName` VARCHAR(45) NULL,
  `FlShipsId` INT NULL,
  PRIMARY KEY (`CaptainId`),
  INDEX `fk_Captain_FlShips1_idx` (`FlShipsId` ASC),
  CONSTRAINT `fk_Captain_FlShips1`
    FOREIGN KEY (`FlShipsId`)
    REFERENCES `IGUN`.`FlShips` (`FlShipsId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IGUN`.`Sanction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IGUN`.`Sanction` ;

CREATE TABLE IF NOT EXISTS `IGUN`.`Sanction` (
  `SanctionId` INT NOT NULL,
  `SanctionName` VARCHAR(45) NULL,
  `EstabDate` DATE NULL,
  PRIMARY KEY (`SanctionId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IGUN`.`SanctionEnforcer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IGUN`.`SanctionEnforcer` ;

CREATE TABLE IF NOT EXISTS `IGUN`.`SanctionEnforcer` (
  `RaceId` INT NOT NULL,
  `SanctionId` INT NOT NULL,
  PRIMARY KEY (`SanctionId`, `RaceId`),
  INDEX `fk_SanctionRace_Race1_idx` (`RaceId` ASC),
  INDEX `fk_SanctionRace_Sanction1_idx` (`SanctionId` ASC),
  CONSTRAINT `fk_SanctionRace_Race1`
    FOREIGN KEY (`RaceId`)
    REFERENCES `IGUN`.`Race` (`RaceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SanctionRace_Sanction1`
    FOREIGN KEY (`SanctionId`)
    REFERENCES `IGUN`.`Sanction` (`SanctionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IGUN`.`Vehicle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IGUN`.`Vehicle` ;

CREATE TABLE IF NOT EXISTS `IGUN`.`Vehicle` (
  `VehicleId` INT NOT NULL,
  `MilFleetId` INT NULL,
  `Speed` INT NULL,
  `CrewCap` INT NULL,
  PRIMARY KEY (`VehicleId`),
  INDEX `fk_Vehicle_MilFleet1_idx` (`MilFleetId` ASC),
  CONSTRAINT `fk_Vehicle_MilFleet1`
    FOREIGN KEY (`MilFleetId`)
    REFERENCES `IGUN`.`MilFleet` (`MilFleetId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IGUN`.`SancConditions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IGUN`.`SancConditions` ;

CREATE TABLE IF NOT EXISTS `IGUN`.`SancConditions` (
  `SancConditionsId` INT NOT NULL,
  `Rule` VARCHAR(1000) NULL,
  `SanctionId` INT NULL,
  PRIMARY KEY (`SancConditionsId`),
  INDEX `fk_SancConditions_Sanction1_idx` (`SanctionId` ASC),
  CONSTRAINT `fk_SancConditions_Sanction1`
    FOREIGN KEY (`SanctionId`)
    REFERENCES `IGUN`.`Sanction` (`SanctionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IGUN`.`SanctionTarget`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IGUN`.`SanctionTarget` ;

CREATE TABLE IF NOT EXISTS `IGUN`.`SanctionTarget` (
  `SanctionId` INT NOT NULL,
  `RaceId` INT NOT NULL,
  PRIMARY KEY (`SanctionId`, `RaceId`),
  INDEX `fk_SanctionTarget_Race1_idx` (`RaceId` ASC),
  CONSTRAINT `fk_SanctionTarget_Sanction1`
    FOREIGN KEY (`SanctionId`)
    REFERENCES `IGUN`.`Sanction` (`SanctionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SanctionTarget_Race1`
    FOREIGN KEY (`RaceId`)
    REFERENCES `IGUN`.`Race` (`RaceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IGUN`.`TradeRoutes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IGUN`.`TradeRoutes` ;

CREATE TABLE IF NOT EXISTS `IGUN`.`TradeRoutes` (
  `TradeRoutesId` INT NOT NULL,
  `Route` VARCHAR(45) NULL,
  `TradeId` INT NOT NULL,
  PRIMARY KEY (`TradeRoutesId`),
  INDEX `fk_TradeRoutes_Trade1_idx` (`TradeId` ASC),
  CONSTRAINT `fk_TradeRoutes_Trade1`
    FOREIGN KEY (`TradeId`)
    REFERENCES `IGUN`.`Trade` (`TradeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IGUN`.`TradePartners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IGUN`.`TradePartners` ;

CREATE TABLE IF NOT EXISTS `IGUN`.`TradePartners` (
  `TradeId` INT NOT NULL,
  `RaceId` INT NOT NULL,
  PRIMARY KEY (`TradeId`, `RaceId`),
  INDEX `fk_TradePartners_Trade1_idx` (`TradeId` ASC),
  INDEX `fk_TradePartners_Race1_idx` (`RaceId` ASC),
  CONSTRAINT `fk_TradePartners_Trade1`
    FOREIGN KEY (`TradeId`)
    REFERENCES `IGUN`.`Trade` (`TradeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TradePartners_Race1`
    FOREIGN KEY (`RaceId`)
    REFERENCES `IGUN`.`Race` (`RaceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
