-- MySQL Script generated by MySQL Workbench
-- 11/17/15 14:12:14
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema IGUN
-- -----------------------------------------------------
USE `IGUN` ;

-- -----------------------------------------------------
-- Table `IGUN`.`Faction`
-- -----------------------------------------------------
REPLACE into `IGUN`.`Faction` values(1,"Triumvirate",true);
REPLACE into `IGUN`.`Faction` values(2,"The Silver Star Accord",true);
REPLACE into `IGUN`.`Faction` values(3,"The Holy Empire of One Thousand Suns",true);
REPLACE into `IGUN`.`Faction` values(4,"The Black Corsairs",false);
REPLACE into `IGUN`.`Faction` values(5,"League of Sorrow", false);
REPLACE into `IGUN`.`Faction` values(6,"The Thirteenth Alliance",true);
REPLACE into `IGUN`.`Faction` values(7,"Galactic Federation",true);
REPLACE into `IGUN`.`Faction` values(8,"Council of Science",true);
REPLACE into `IGUN`.`Faction` values(9,"League of Absolom's Bloody Sword",false);
REPLACE into `IGUN`.`Faction` values(10,"Alliance of Terror",false);
-- -----------------------------------------------------
-- Table `IGUN`.`Race`
-- -----------------------------------------------------
REPLACE into `IGUN`.`Race` values(1,"Terran","One of the three most powerful races in the galaxy, the Terran Race are masters of technology, and perseverance.
             They have spread into the stars for the sake of exploring the unknown.","Homosapien",4550000,"Earth","Terran","President Michael Jackson",1);

REPLACE into `IGUN`.`Race` values(2,"Lumintaran","Following an enlightened path, the Lumintaran Race value intelligence, logic, and wisdom. They have taken to the great beyond seeking to spread enlightenment to the larger galaxy.","Leonid",2300000,"Garatrix Prime","Valdorian","Valedictorian Rama Nebuli",1);

REPLACE into `IGUN`.`Race` values(3,"Practurinean","Super efficient industrialization and an innate sense of THE GREATER GOOD has driven Practurinean society through history.
	     They are excellent engineers. They have ventured into the stars looking for the best new way to make the next greatest thing.","Ridonsapien",7100000,"Hedion","Jaxtor","Founder Brahmin Trok",10);

REPLACE into `IGUN`.`Race` values(4,"Predim"," This is one of the largest races in the galaxy. They are fervent believers in the practiced martial arts. 
	     Through technique and prowess in battle, these warriors gain honor and live fulfilling lives.","Halkorian",23000000,"Bewtoni''tor","Thalmorian","Grand Master Mushu",2);

REPLACE into `IGUN`.`Race` value(5,"Malkonian","Traders extroadinaire. They would sell their own mothers if you paid a fair price. 
	     They wander the stars in great caravans, hawking their wares and and spreading commerce.","Salkosapien",1200000,"Xaqirr","L''Wan","Prelate Hajj Milarr",9);

REPLACE into `IGUN`.`Race` values(6,"Praetorian","Zealously relgious, faithful, and incredibly militant, the Praetorian race seeks to subjugate others and force them to adhere to their Theocratic Empire.
	     They spread the word of their Deity through military conquest.","Khanid",13900000,"Krintar","Holy Namin","Empress Anver Morantia",3);

REPLACE into `IGUN`.`Race` values(7,"Phoriid","A protectorate of the Praetorian species, they are considered to be inferior in every way, and hold fewer rights in theocratic society than the Praetorians.
	     They live to serve the Empire in every way.","Krintorian",2000000,"Drimini","Holy Namin","Empress Aner Morantia",4);

REPLACE into `IGUN`.`Race` values(8,"Olphin","Bloodthirsty, and vicious, the Olphin race is a large band of miscreants and deviants. They have no values, or morals.
	     Many devolve into becoming space pirates. They are the scum of the galaxy.","Yaktruid",31700,"Ord","Falkun","Admiral Rem",5);

REPLACE into `IGUN`.`Race` values(9,"Chozo","Wise and peaceful, the Chozo live only to create and to discover. They bring great artifacts of science with them wherever they go and are respected by all.","Avianid",900000,"Zebes","Choriak","Ilmet-D",6);

REPLACE into `IGUN`.`Race` values(10,"Sikeerian","A mystical race with very few members. They occupy only one planet far removed from the territories of most other civilized races. Little is known about them but it is said that they posses fearsome powers of the mind and their military might is great, should they ever need it.","Paroniad",8000,"Kolin-7","Sikomo","Unsar Ishtunar Valforsen",7);

-- -----------------------------------------------------
-- Table `IGUN`.`FacConditions` conditionId,FactionId,Rule
-- -----------------------------------------------------

REPLACE into `IGUN`.`FacConditions` values(1,1,"Acceptance into the group must be mutually accepted.");

REPLACE into `IGUN`.`FacConditions` values(1,1,"Let's all just get along.");

REPLACE into `IGUN`.`FacConditions` values(1,1,"Condition.");

REPLACE into `IGUN`.`FacConditions` values(2,1,"Non-Aggression");
REPLACE into `IGUN`.`FacConditions` values(2,1,"Un-Aggression");
REPLACE into `IGUN`.`FacConditions` values(2,1,"No-Aggression");
REPLACE into `IGUN`.`FacConditions` values(2,1,"NO");

REPLACE into `IGUN`.`FacConditions` values(3,1,"No member shall develope weapons in secret, hidden from the other members");
REPLACE into `IGUN`.`FacConditions` values(3,1,"Don't kill each other");

REPLACE into `IGUN`.`FacConditions` values(3,1,"No member shall develope weapons in secret, hidden from the other members");

REPLACE into `IGUN`.`FacConditions` values(4,3,"Blasphemy is cause for extermination of offending member");

REPLACE into `IGUN`.`FacConditions` values(5,4,"Thou must be a pirate");

REPLACE into `IGUN`.`FacConditions` values(6,8,"All members are must be dedicated to the progression of science.");

REPLACE into `IGUN`.`FacConditions` values(7,7,"All members must be periodically subject to investigation.");

REPLACE into `IGUN`.`FacConditions` values(8,5,"Conquered planets will become territory of all members jointly");

REPLACE into `IGUN`.`FacConditions` values(9,6,"All members must engage in occasional miliray exercises with one another");

REPLACE into `IGUN`.`FacConditions` values(10,9,"All opposition must die");
-- -----------------------------------------------------
-- Table `IGUN`.`SpaceStation` SpaceStationId, use(civ,mil),Population,shipcap,flightcraftcap,industrialcap,raceId
-- -----------------------------------------------------
REPLACE into `IGUN`.`SpaceStation` values(1, 'civ', 3000, 100, 1000, 'Y', 5);
REPLACE into `IGUN`.`SpaceStation` values(2, 'mil', 40000, 2000, 9300, 'Y', 1);
REPLACE into `IGUN`.`SpaceStation` values(3, 'mil', 120, 10, 2900, 'N', 1);
REPLACE into `IGUN`.`SpaceStation` values(4, 'civ', 9470, 9000, 130, 'N', 2);
REPLACE into `IGUN`.`SpaceStation` values(5, 'civ', 443, 200, 340, 'Y', 6);
REPLACE into `IGUN`.`SpaceStation` values(6, 'mil', 4340, 3400, 9040, 'N', 4);
REPLACE into `IGUN`.`SpaceStation` values(7, 'civ', 530, 90, 32400, 'Y', 7);
REPLACE into `IGUN`.`SpaceStation` values(8, 'mil', 120, 7000, 5400, 'N', 9);
REPLACE into `IGUN`.`SpaceStation` values(9, 'civ', 330, 10000, 100, 'N', 7);
REPLACE into `IGUN`.`SpaceStation` values(10, 'civ', 410, 23000, 9300, 'N', 7);
-- -----------------------------------------------------
-- Table `IGUN`.`Sov` SovId,name,RaceId
-- -----------------------------------------------------
REPLACE into `IGUN`.`Sov` values(1,"Space America",1);
REPLACE into `IGUN`.`Sov` values(2,"Lumintaria",2);
REPLACE into `IGUN`.`Sov` values(3,"Olphin Empire",8);
REPLACE into `IGUN`.`Sov` values(4,"Holy Domain of Namin",6);
REPLACE into `IGUN`.`Sov` values(5,"Region 7",3);
REPLACE into `IGUN`.`Sov` values(6,"Prearia",4);
REPLACE into `IGUN`.`Sov` values(7,"Malkonian Realm",5);
REPLACE into `IGUN`.`Sov` values(8,"Velarin",10);
REPLACE into `IGUN`.`Sov` values(9,"Chozodia",9);
REPLACE into `IGUN`.`Sov` values(10,"Phoridit",7);
-- -----------------------------------------------------
-- Table `IGUN`.`StarSys` StarSysId,planetNum,Resources,SovId,Population,Diameter
-- -----------------------------------------------------
REPLACE into `IGUN`.`StarSys` values(1,30,null,3,90000,43);
REPLACE into `IGUN`.`StarSys` values(2,700,null,1,435000,4353);
REPLACE into `IGUN`.`StarSys` values(3,9,null,3,103030,46);
REPLACE into `IGUN`.`StarSys` values(4,3,null,4,10032,20);
REPLACE into `IGUN`.`StarSys` values(5,56,null,7,45620,90);
REPLACE into `IGUN`.`StarSys` values(6,72,null,10,763500,300);
REPLACE into `IGUN`.`StarSys` values(7,821,null,9,700560,23);
REPLACE into `IGUN`.`StarSys` values(8,123,null,6,72345,143);
REPLACE into `IGUN`.`StarSys` values(9,2,null,1,854000,10);
REPLACE into `IGUN`.`StarSys` values(10,283,null,2,810,342);
REPLACE into `IGUN`.`StarSys` values(11,283,null,5,810,342);
REPLACE into `IGUN`.`StarSys` values(12,283,null,8,810,342);
-- -----------------------------------------------------
-- Table `IGUN`.`Planet` PlanetId, size, density, mass, name, type, atmosphere, gravity, colonized, loclanguage, population, Starsysid
-- -----------------------------------------------------
REPLACE into `IGUN`.`Planet` values(1,32,45,352,"Tel","Gas",null,2.1,true,"Tellian",342,6);

REPLACE into `IGUN`.`Planet` values(16,324,123,737,"Marth","Molten",null,345.1,true,"Marthian",342,6);

REPLACE into `IGUN`.`Planet` values(20,24352,13,747,"The Snerkel-9","Molten",null,345.121,true,"What do you want from me?",342235234,6);

REPLACE into `IGUN`.`Planet` values(2,32,4436,456,"Doth","Gas",null,2.1,true,"Dothic",342,7);

REPLACE into `IGUN`.`Planet` values(11,345,436,46,"Zebes","Terrestrial",null,42.1,true,"Zebesian",23452,7);


REPLACE into `IGUN`.`Planet` values(3,10045,65,546,"Feliad","Gas",null,352.1435,true,"Felirian",342,1);

REPLACE into `IGUN`.`Planet` values(12,10045,65,546,"Fat","Gas",null,352.1435,true,"Felirian",342,1);

REPLACE into `IGUN`.`Planet` values(13,10045,65,546,"Fat2","Gas",null,352.1435,true,"Felirian",342,1);

REPLACE into `IGUN`.`Planet` values(4,4357,456,65,"_UNIDENTIFIED_",null,null,234.1,false,null,null,2);

REPLACE into `IGUN`.`Planet` values(21,434557,4,115,"_11111111111_",null,null,234.1,false,null,null,2);

REPLACE into `IGUN`.`Planet` values(5,467,74,45674345,"XX-0-32","Barren",null,.134,false,null,0,3);

REPLACE into `IGUN`.`Planet` values(14,237,7234,44345,"YXU-9-O6-9000","Frozen",null,511.134,false,null,0,3);

REPLACE into `IGUN`.`Planet` values(6,67,562,65456,"Letver","Molten",null,24.0001,true,"Verian",3344,5);

REPLACE into `IGUN`.`Planet` values(6,67,562,65456,"Planet Edward","Dwarf",null,24.0001,true,"Ulmet",3344,5);

REPLACE into `IGUN`.`Planet` values(30,4,554,4731544,"Filmath","Frozen",null,0.12,true,"Filmarin",4653,8);
REPLACE into `IGUN`.`Planet` values(31,4,554,48,"Tourian","Frozen",null,0.12,true,"Tourith",4653,8);
REPLACE into `IGUN`.`Planet` values(32,4,554,854,"Maridia","Frozen",null,0.12,true,"Rimiar",4653,8);
REPLACE into `IGUN`.`Planet` values(33,4,554,8544,"Sreeech","Frozen",null,0.12,true,"SCREAM",4653,8);
REPLACE into `IGUN`.`Planet` values(34,4,554,4744,"Pepper","Frozen",null,0.12,true,"Pepperian",4653,8);


REPLACE into `IGUN`.`Planet` values(8,44,468,99999999,"Beltrag","Water",null,45.999,true,"Beltoric",23452,9);

REPLACE into `IGUN`.`Planet` values(9,3452,684,2342,"Goltan","Dry",null,345345.342,true,"Goltish",3242312,9);

REPLACE into `IGUN`.`Planet` values(10,34,4535,30000000,"X98GF-3","Molten",null,300.12,false,null,null,4);
REPLACE into `IGUN`.`Planet` values(99,234,453,1,"Decoy Planet","Molten",null,300.12,false,null,null,4);

REPLACE into `IGUN`.`Planet` values(100,234,453,1,"Norion","Molten",null,300.12,false,null,null,10);
REPLACE into `IGUN`.`Planet` values(101,3452,684,2342,"Elysia","Dry",null,345345.342,true,"Elysian",3242312,10);
REPLACE into `IGUN`.`Planet` values(102,44,468,99999999,"Aether","Water",null,45.999,true,"Luminoth",23452,10);

REPLACE into `IGUN`.`Planet` values(103,24,4234,99,"Hat","Water",null,45.999,true,"Hat",23452,11);

REPLACE into `IGUN`.`Planet` values(102,22345,118,939999,"Galerin","Water",null,45.999,true,"Galerian",23452,12);

REPLACE into `IGUN`.`Planet` values(104,22345,118,939999,"Earth","Terrestrial",null,45.999,true,"English",23452,9);
REPLACE into `IGUN`.`Planet` values(105,22345,118,939999,"Garatrix Prime","Terrestrial",null,45.999,true,"Valdorian",23452,10);
REPLACE into `IGUN`.`Planet` values(106,22345,118,939999,"Hedion","Gas",null,45.999,true,"Jaxtor",23452,1);
REPLACE into `IGUN`.`Planet` values(107,22345,118,939999,"Bewtoni''tor","Terrestrial",null,45.999,true,"Thalmorian",23452,4);

REPLACE into `IGUN`.`Planet` values(112,22345,118,939999,"Xaqirr","Terrestrial",null,45.999,true,"L''Wan",23452,11);

REPLACE into `IGUN`.`Planet` values(108,22345,118,939999,"Krintar","Terrestrial",null,45.999,true,"Holy Namin",23452,8);

REPLACE into `IGUN`.`Planet` values(109,22345,118,939999,"Drimini","Ocean",null,45.999,true,"Holy Namin",23452,5);

REPLACE into `IGUN`.`Planet` values(110,22345,118,939999,"Ord","Terrestrial",null,45.999,true,"Falkun",23452,12);

REPLACE into `IGUN`.`Planet` values(111,22345,118,939999,"Kolin-7","Frozen",null,45.999,true,"Sikomo",23452,6);


-- -----------------------------------------------------
-- Table `IGUN`.`Moon` MoonId, Name,size,density, mass, type, atmosphere, gravity, inhabited, population, planetId
-- terrestrial, gas, molten, frozen, desert, oceanic, storm
-- -----------------------------------------------------
REPLACE into `IGUN`.`Moon` values(1,"Kilm",32,3245,12,'Storm',null,39.0,'N',0,8);

REPLACE into `IGUN`.`Moon` values(11,"Turkery",54,12412,565,'Terrestrial',null,900.1,'Y',124,'8');

REPLACE into `IGUN`.`Moon` values(2,"Akihabara",23,2345,132,'Terrestrial',null,39.0,'N',0,9);

REPLACE into `IGUN`.`Moon` values(3,"Kokoro",3456,32,124,'Frozen',null,39.0,'N',0,10);

REPLACE into `IGUN`.`Moon` values(4,"Crimea",532,343245,412,'Terrestrial',null,39.0,'N',0,3);

REPLACE into `IGUN`.`Moon` values(5,"Hollen",352,2,4,'Desert',null,39.0,'N',0,4);

REPLACE into `IGUN`.`Moon` values(6,"Goldoa",5,54,1436,'Storm',null,39.0,'N',0,2);

REPLACE into `IGUN`.`Moon` values(7,"Galroa",5632,32345,1362,'Gas',null,39.0,'N',0,1);

REPLACE into `IGUN`.`Moon` values(8,"Morsa",4532,56345,143,'Oceanic',null,39.0,'N',0,5);

REPLACE into `IGUN`.`Moon` values(9,"Amestris",334,35,32,'Terrestrial',null,39.0,'N',0,6);

REPLACE into `IGUN`.`Moon` values(10,"Dracma",3456,455,14,'Frozen',null,39.0,'N',0,7);

REPLACE into `IGUN`.`Moon` values(11,"Poultry",3456,455,14,'Frozen',null,39.0,'N',0,12);

REPLACE into `IGUN`.`Moon` values(12,"Xing",3456,455,14,'Frozen',null,39.0,'N',0,13);

REPLACE into `IGUN`.`Moon` values(13,"Miseration",3456,455,14,'Frozen',null,39.0,'N',0,21);

REPLACE into `IGUN`.`Moon` values(14,"Begnion",5632,32345,1362,'Gas',null,39.0,'N',0,14);

REPLACE into `IGUN`.`Moon` values(15,"Phoenicias",5632,32345,1362,'Gas',null,39.0,'N',0,103);

REPLACE into `IGUN`.`Moon` values(16,"Mekakushi",5632,32345,1362,'Gas',null,39.0,'N',0,16);

REPLACE into `IGUN`.`Moon` values(17,"Death",5632,32345,1362,'Gas',null,39.0,'N',0,20);

REPLACE into `IGUN`.`Moon` values(18,"Cern",5632,32345,1362,'Gas',null,39.0,'N',0,11);

REPLACE into `IGUN`.`Moon` values(19,"Westminser",5632,32345,1362,'Terrestrial',null,39.0,'N',0,30);

REPLACE into `IGUN`.`Moon` values(20,"Kilvas",5632,32345,1362,'Gas',null,39.0,'N',0,31);

REPLACE into `IGUN`.`Moon` values(21,"Beleriand",5632,32345,1362,'Gas',null,39.0,'N',0,32);

REPLACE into `IGUN`.`Moon` values(22,"Moria",5632,32345,1362,'Gas',null,39.0,'N',0,33);

REPLACE into `IGUN`.`Moon` values(23,"Mordor",5632,32345,1362,'Gas',null,39.0,'N',0,34);

REPLACE into `IGUN`.`Moon` values(24,"Lothlorien",5632,32345,1362,'Gas',null,39.0,'N',0,100);

REPLACE into `IGUN`.`Moon` values(25,"Valinor",5632,32345,1362,'Gas',null,39.0,'N',0,101);

REPLACE into `IGUN`.`Moon` values(26,"Dol Goldur",5632,32345,1362,'Gas',null,39.0,'N',0,102);

REPLACE into `IGUN`.`Moon` values(300,"Monolith",5632,32345,1362,'Gas',null,39.0,'N',0,99);


REPLACE into `IGUN`.`Moon` values(301,"Tear Gas",5632,32345,1362,'Gas',null,39.0,'N',0,99);


-- -----------------------------------------------------
-- Table `IGUN`.`Sanction` SanctionId,sanctionName, estabDate
-- -----------------------------------------------------
REPLACE into `IGUN`.`Sanction` value(1,"WMD Sanction",'2321/6/4');

REPLACE into `IGUN`.`Sanction` value(2,"Act 337",'6666/8/15');

REPLACE into `IGUN`.`Sanction` value(3,"Alliance Sanction",'7777/7/25');

REPLACE into `IGUN`.`Sanction` value(4,"Sanction against pirate supporters",'3453/10/27');

REPLACE into `IGUN`.`Sanction` value(5,"X-sanction 339-",'1221/3/3');

REPLACE into `IGUN`.`Sanction` value(6,"Act 902",'2321/9/2');

REPLACE into `IGUN`.`Sanction` value(7,"Chemical warfare Sanction",'4521/4/18');

REPLACE into `IGUN`.`Sanction` value(8,"Violently enforced",'9394/10/7');


REPLACE into `IGUN`.`Sanction` value(9,"Unjust",'2334/11/23');

REPLACE into `IGUN`.`Sanction` value(10,"Justice",'1334/12/14');

-- -----------------------------------------------------
-- Table `IGUN`.`SancConditions` SancConditionId,rule, sancId
-- -----------------------------------------------------
REPLACE into `IGUN`.`SancConditions` value(1, "Do not break the rules", 1);

REPLACE into `IGUN`.`SancConditions` value(2, "SILENCE", 1);

REPLACE into `IGUN`.`SancConditions` value(3, "Unjust", 2);

REPLACE into `IGUN`.`SancConditions` value(4, "U", 2);

REPLACE into `IGUN`.`SancConditions` value(5, "N", 2);

REPLACE into `IGUN`.`SancConditions` value(6, "J", 2);

REPLACE into `IGUN`.`SancConditions` value(7, "U", 2);

REPLACE into `IGUN`.`SancConditions` value(8, "S", 2);

REPLACE into `IGUN`.`SancConditions` value(9, "T", 2);

REPLACE into `IGUN`.`SancConditions` value(10, "AAAAH", 2);

REPLACE into `IGUN`.`SancConditions` value(11, "Don't be a 
pirate", 2);

REPLACE into `IGUN`.`SancConditions` value(12, "Pleas understand", 2);

REPLACE into `IGUN`.`SancConditions` value(13, "Give me food", 2);

REPLACE into `IGUN`.`SancConditions` value(14, "tsujnu", 2);

REPLACE into `IGUN`.`SancConditions` value(15, "Chicken", 2);

REPLACE into `IGUN`.`SancConditions` value(16, "Rabbit", 2);

REPLACE into `IGUN`.`SancConditions` value(17, "First condition", 3);

REPLACE into `IGUN`.`SancConditions` value(18, "Second condition", 3);

REPLACE into `IGUN`.`SancConditions` value(19, "Be careful what you wish for", 4);

REPLACE into `IGUN`.`SancConditions` value(20, "You cannot pass", 4);

REPLACE into `IGUN`.`SancConditions` value(21, "Gandalf", 4);
REPLACE into `IGUN`.`SancConditions` value(22, "Watch it", 5);
REPLACE into `IGUN`.`SancConditions` value(23, "Don't watch it", 5);
REPLACE into `IGUN`.`SancConditions` value(24, "afasdfshdf", 5);
REPLACE into `IGUN`.`SancConditions` value(25, "This condition is very serious", 6);
REPLACE into `IGUN`.`SancConditions` value(26, "So is this one", 6);
REPLACE into `IGUN`.`SancConditions` value(27, "And this one", 6);
REPLACE into `IGUN`.`SancConditions` value(28, "Not this one though", 6);
REPLACE into `IGUN`.`SancConditions` value(29, "rules rules rules", 7);
REPLACE into `IGUN`.`SancConditions` value(30, "conditions conditions conditions", 7);
REPLACE into `IGUN`.`SancConditions` value(31, "RUUUULES", 7);
REPLACE into `IGUN`.`SancConditions` value(32, "Bad dog", 8);
REPLACE into `IGUN`.`SancConditions` value(33, "Commandment", 8);
REPLACE into `IGUN`.`SancConditions` value(34, "Listen up", 8);
REPLACE into `IGUN`.`SancConditions` value(35, "Don't do this stuff", 8);
REPLACE into `IGUN`.`SancConditions` value(36, "Please no", 8);
REPLACE into `IGUN`.`SancConditions` value(37, "Well then", 8);
REPLACE into `IGUN`.`SancConditions` value(38, "Seriously?", 8);
REPLACE into `IGUN`.`SancConditions` value(39, "...", 9);
REPLACE into `IGUN`.`SancConditions` value(40, "Command", 9);
REPLACE into `IGUN`.`SancConditions` value(41, "Command", 9);
REPLACE into `IGUN`.`SancConditions` value(42, "You have done bad", 10);
REPLACE into `IGUN`.`SancConditions` value(43, "NO", 10);
REPLACE into `IGUN`.`SancConditions` value(44, "You wretch", 10);
REPLACE into `IGUN`.`SancConditions` value(45, "I disagree", 10);
-- -----------------------------------------------------
-- Table `IGUN`.`SanctionEnforcer` SancConditionId,raceId, sancId
-- -----------------------------------------------------
REPLACE into `IGUN`.`SanctionEnforcer` values(1,2);
REPLACE into `IGUN`.`SanctionEnforcer` values(3,4);
REPLACE into `IGUN`.`SanctionEnforcer` values(5,9);
REPLACE into `IGUN`.`SanctionEnforcer` values(6,9);
REPLACE into `IGUN`.`SanctionEnforcer` values(7,9);
REPLACE into `IGUN`.`SanctionEnforcer` values(1,3);
REPLACE into `IGUN`.`SanctionEnforcer` values(1,5);
REPLACE into `IGUN`.`SanctionEnforcer` values(4,2);
REPLACE into `IGUN`.`SanctionEnforcer` values(2,10);
REPLACE into `IGUN`.`SanctionEnforcer` values(10,10);
-- -----------------------------------------------------
-- Table `IGUN`.`SanctionTarget` SancConditionId,sanctionId, raceId
-- -----------------------------------------------------
REPLACE into `IGUN`.`SanctionTarget` values(10,10);
REPLACE into `IGUN`.`SanctionTarget` values(9,10);
REPLACE into `IGUN`.`SanctionTarget` values(8,10);
REPLACE into `IGUN`.`SanctionTarget` values(4,3);
REPLACE into `IGUN`.`SanctionTarget` values(4,7);
REPLACE into `IGUN`.`SanctionTarget` values(1,4);
REPLACE into `IGUN`.`SanctionTarget` values(5,6);
REPLACE into `IGUN`.`SanctionTarget` values(6,3);
REPLACE into `IGUN`.`SanctionTarget` values(8,5);
REPLACE into `IGUN`.`SanctionTarget` values(9,5);

-- -----------------------------------------------------
-- Table `IGUN`.`Trade` TradeId,TradeProfit,RaceId
-- -----------------------------------------------------
REPLACE into `IGUN`.`Trade` values(1,50000,1);
REPLACE into `IGUN`.`Trade` values(2,60000,8);
REPLACE into `IGUN`.`Trade` values(3,3450000,7);
REPLACE into `IGUN`.`Trade` values(4,5500,2);
REPLACE into `IGUN`.`Trade` values(5,850000,10);
REPLACE into `IGUN`.`Trade` values(6,810000,9);
REPLACE into `IGUN`.`Trade` values(7,7000000,6);
REPLACE into `IGUN`.`Trade` values(8,990000,5);
REPLACE into `IGUN`.`Trade` values(9,40000,4);
REPLACE into `IGUN`.`Trade` values(10,9999999,3);

-- -----------------------------------------------------
-- Table `IGUN`.`TradeRoutes` TradeRoutesId,Route,TradeId
-- -----------------------------------------------------
REPLACE into `IGUN`.`TradeRoutes` values(1,"Through the Holy Domain of Namin",6);
REPLACE into `IGUN`.`TradeRoutes` values(2,"Around the Yeren Belt",5);
REPLACE into `IGUN`.`TradeRoutes` values(3,"Straight ahead",4);
REPLACE into `IGUN`.`TradeRoutes` values(4,"Undisclosed",8);
REPLACE into `IGUN`.`TradeRoutes` values(5,"Throught an advanced wormhole generator",3);
REPLACE into `IGUN`.`TradeRoutes` values(6,"Past the Gilfar System",9);
REPLACE into `IGUN`.`TradeRoutes` values(7,"Backwards",7);
REPLACE into `IGUN`.`TradeRoutes` values(8,"Cutting through the Kilama Region",10);
REPLACE into `IGUN`.`TradeRoutes` values(9,"Between Sector 77-X and Region 7",2);
REPLACE into `IGUN`.`TradeRoutes` values(10,"Take a left",1);
-- -----------------------------------------------------
-- Table `IGUN`.`TradePartners` TradeId,PartnerId
-- -----------------------------------------------------
REPLACE into `IGUN`.`TradePartners` values(10,1);
REPLACE into `IGUN`.`TradePartners` values(10,2);
REPLACE into `IGUN`.`TradePartners` values(10,3);
REPLACE into `IGUN`.`TradePartners` values(7,4);
REPLACE into `IGUN`.`TradePartners` values(7,9);
REPLACE into `IGUN`.`TradePartners` values(7,7);
REPLACE into `IGUN`.`TradePartners` values(7,10);
REPLACE into `IGUN`.`TradePartners` values(1,1);
REPLACE into `IGUN`.`TradePartners` values(1,4);
REPLACE into `IGUN`.`TradePartners` values(8,9);
REPLACE into `IGUN`.`TradePartners` values(8,5);
REPLACE into `IGUN`.`TradePartners` values(2,1);
REPLACE into `IGUN`.`TradePartners` values(2,7);
REPLACE into `IGUN`.`TradePartners` values(4,6);
REPLACE into `IGUN`.`TradePartners` values(4,3);
REPLACE into `IGUN`.`TradePartners` values(3,2);
REPLACE into `IGUN`.`TradePartners` values(3,5);
REPLACE into `IGUN`.`TradePartners` values(3,8);
REPLACE into `IGUN`.`TradePartners` values(3,10);
-- -----------------------------------------------------
-- Table `IGUN`.`Military` MilitaryId, FleetSize, GroundForceSize, RaceId
-- -----------------------------------------------------
REPLACE into `IGUN`.`Military` values(1,1000,83700,1);
REPLACE into `IGUN`.`Military` values(2,343000,56700,2);
REPLACE into `IGUN`.`Military` values(3,7650,9200,3);
REPLACE into `IGUN`.`Military` values(4,767000,5600,4);
REPLACE into `IGUN`.`Military` values(5,8300,5400,5);
REPLACE into `IGUN`.`Military` values(6,567000,4400,6);
REPLACE into `IGUN`.`Military` values(7,24000,400,7);
REPLACE into `IGUN`.`Military` values(8,59000,2300,8);
REPLACE into `IGUN`.`Military` values(9,9000,34300,9);
REPLACE into `IGUN`.`Military` values(10,46000,3400,10);
-- -----------------------------------------------------
-- Table `IGUN`.`MilCom` MilComId, ComFirstName, ComLastName, MilitaryId
-- -----------------------------------------------------
REPLACE into `IGUN`.`MilCom` values(1,"Shal","Kisvudar",10);
REPLACE into `IGUN`.`MilCom` values(2,"Halsa-Q",null,9);
REPLACE into `IGUN`.`MilCom` values(3,"Kilver","Baradani",7);
REPLACE into `IGUN`.`MilCom` values(4,"Kor","Bilmok",3);
REPLACE into `IGUN`.`MilCom` values(5,"Garr","Childakk",5);
REPLACE into `IGUN`.`MilCom` values(6,"Iq'van","Udoru",4);
REPLACE into `IGUN`.`MilCom` values(7,"Kanye","West",1);
REPLACE into `IGUN`.`MilCom` values(8,"Kyouma","Kokador",2);
REPLACE into `IGUN`.`MilCom` values(9,"Yer","Kenmar",6);
REPLACE into `IGUN`.`MilCom` values(10,"Shintaro","Kisaragi",8);

-- -----------------------------------------------------
-- Table `IGUN`.`MilFleet` MilFleetId, FleetName, NumShips, NumPersonnel, MilitaryId
-- -----------------------------------------------------
REPLACE into `IGUN`.`MilFleet` values(1,"First Terran Fleet",356000,467000,1);

REPLACE into `IGUN`.`MilFleet` values(2,"Fleet Lumintar-33X",46000,65000,2);

REPLACE into `IGUN`.`MilFleet` values(3,"XX-7-3-Prac",643000,67000,3);

REPLACE into `IGUN`.`MilFleet` values(4,"Group 9",76000,5680,4);

REPLACE into `IGUN`.`MilFleet` values(5,"Convoy",48400,678000,5);

REPLACE into `IGUN`.`MilFleet` values(6,"Zealot Convoy",107540,100450,6);

REPLACE into `IGUN`.`MilFleet` values(7,"Slave Legion",1650,15700,7);

REPLACE into `IGUN`.`MilFleet` values(8,"Marauder Band 3",53400,13500,8);

REPLACE into `IGUN`.`MilFleet` values(9,"Chozo Fleet",2000,34000,9);

REPLACE into `IGUN`.`MilFleet` values(10,"Omelette",345000,5600,10);
-- -----------------------------------------------------
-- Table `IGUN`.`Admiral`AdmiralId,AdFirstName,AdLastName,milFleetId
-- -----------------------------------------------------
REPLACE into `IGUN`.`Admiral` values(1,"Well","Max",1);
REPLACE into `IGUN`.`Admiral` values(3,"Cura","Vilnax",2);
REPLACE into `IGUN`.`Admiral` values(3,"Galfetch","Tilbran",3);
REPLACE into `IGUN`.`Admiral` values(4,"Luta","Dikira",4);
REPLACE into `IGUN`.`Admiral` values(5,"For'twi","Balsath",5);
REPLACE into `IGUN`.`Admiral` values(6,"Ish","Kilimath",6);
REPLACE into `IGUN`.`Admiral` values(7,"Fald","Yos",7);
REPLACE into `IGUN`.`Admiral` values(8,"Tsubomi","Ohperius",8);
REPLACE into `IGUN`.`Admiral` values(9,null,"Velth-Y",9);
REPLACE into `IGUN`.`Admiral` values(10,"Nara","Shimeru",10);
-- -----------------------------------------------------
-- Table `IGUN`.`Vehicle` VehicleId,MilFleetId,Speed,CrewCap
-- -----------------------------------------------------
REPLACE into `IGUN`.`Vehicle` values(1,1,100,11);
REPLACE into `IGUN`.`Vehicle` values(2,2,1000,32);
REPLACE into `IGUN`.`Vehicle` values(3,3,300,61);
REPLACE into `IGUN`.`Vehicle` values(4,4,50,8);
REPLACE into `IGUN`.`Vehicle` values(5,5,430,4);
REPLACE into `IGUN`.`Vehicle` values(6,6,117,34);
REPLACE into `IGUN`.`Vehicle` values(7,7,34,1);
REPLACE into `IGUN`.`Vehicle` values(8,8,40,29);
REPLACE into `IGUN`.`Vehicle` values(9,9,7,17);
REPLACE into `IGUN`.`Vehicle` values(10,10,103,3);
REPLACE into `IGUN`.`Vehicle` values(11,1,1111,5);
REPLACE into `IGUN`.`Vehicle` values(12,2,129,4);
REPLACE into `IGUN`.`Vehicle` values(13,2,129,4);
REPLACE into `IGUN`.`Vehicle` values(14,2,129,4);
REPLACE into `IGUN`.`Vehicle` values(15,2,129,4);
REPLACE into `IGUN`.`Vehicle` values(16,2,129,4);
REPLACE into `IGUN`.`Vehicle` values(17,2,129,4);
REPLACE into `IGUN`.`Vehicle` values(18,2,129,4);
REPLACE into `IGUN`.`Vehicle` values(19,2,129,4);
REPLACE into `IGUN`.`Vehicle` values(20,2,129,4);
REPLACE into `IGUN`.`Vehicle` values(21,2,129,4);
REPLACE into `IGUN`.`Vehicle` values(22,2,129,4);
REPLACE into `IGUN`.`Vehicle` values(23,2,129,4);
REPLACE into `IGUN`.`Vehicle` values(24,2,129,4);
REPLACE into `IGUN`.`Vehicle` values(25,2,129,4);
REPLACE into `IGUN`.`Vehicle` values(26,2,129,4);
REPLACE into `IGUN`.`Vehicle` values(27,2,129,4);
REPLACE into `IGUN`.`Vehicle` values(28,2,129,4);
REPLACE into `IGUN`.`Vehicle` values(29,2,129,4);
REPLACE into `IGUN`.`Vehicle` values(30,2,129,4);
-- -----------------------------------------------------
-- Table `IGUN`.`Flcraft` FlCraftId, vehicleId type(fighter,shuttle, bomber), size, armament
-- -----------------------------------------------------
REPLACE into `IGUN`.`Flcraft` values(1,1,'Shuttles',34,null);

REPLACE into `IGUN`.`Flcraft` values(2,2,'Bombers',43,"Light Bomb");

REPLACE into `IGUN`.`Flcraft` values(3,3,'Shuttles',56,"Peanut");

REPLACE into `IGUN`.`Flcraft` values(4,4,'Shuttles',674,"Small Gun");

REPLACE into `IGUN`.`Flcraft` values(5,5,'Fighters',564,"Normal Gun");

REPLACE into `IGUN`.`Flcraft` values(6,6,'Fighters',45,"Antimatter cannon");

REPLACE into `IGUN`.`Flcraft` values(7,7,'Bombers',2,"Nuclear warhead");

REPLACE into `IGUN`.`Flcraft` values(8,8,'Shuttles',58,null);

REPLACE into `IGUN`.`Flcraft` values(9,9,'Bombers',96,"EMP Bombs");

REPLACE into `IGUN`.`Flcraft` values(10,10,'Bombers',87,"Plasma Cannon");
-- -----------------------------------------------------
-- Table `IGUN`.`FlShips` flshipId,vehicleId,shipname,classification,tier (frigate,desroyer,cruiser,battleship,carrier,dreadnaught), size, armament
-- -----------------------------------------------------
REPLACE into `IGUN`.`FlShips` values(1,11,"Bloody Rogue",null,'Dreadnaught',32,"Super Death Cannon");

REPLACE into `IGUN`.`FlShips` values(2,12,"Golden Night",null,'Battleship',133,"Nuclear Cannon");

REPLACE into `IGUN`.`FlShips` values(3,13,"Hand of Fire",null,'Cruiser',723,"Fission Cannon");

REPLACE into `IGUN`.`FlShips` values(4,14,"FAST SHIP",null,'Carrier',9523,"FAST GUN");

REPLACE into `IGUN`.`FlShips` values(5,15,"Kura's Spear",null,'Frigate',8462,"Spear Cannon");

REPLACE into `IGUN`.`FlShips` values(6,16,"Xeveriand",null,'Carrier',7381,"Terror Master Blaster");

REPLACE into `IGUN`.`FlShips` values(7,17,"Nova",null,'Carrier',48,"''Moltenator''");

REPLACE into `IGUN`.`FlShips` values(8,18,"Black Star",null,'Dreadnaught',26475,"Anti-Matter Cannon");

REPLACE into `IGUN`.`FlShips` values(9,19,"8X-9O-33R",null,'Dreadnaught',2243,"555-R3-Model 9");

REPLACE into `IGUN`.`FlShips` values(10,20,"Angband",null,'Dreadnaught',613,"Magic Gun");
-- -----------------------------------------------------
-- Table `IGUN`.`Flground`  flgroundId,Structure,Mainweapon
-- -----------------------------------------------------
REPLACE into `IGUN`.`Flground` values(1,21,"Wheeled","Magic Gun");
REPLACE into `IGUN`.`Flground` values(2,22,"Wheeled","Machine Gun");
REPLACE into `IGUN`.`Flground` values(3,23,"Walker","Gatling Gun");
REPLACE into `IGUN`.`Flground` values(4,24,"Levitation","Laser Cannon");
REPLACE into `IGUN`.`Flground` values(5,25,"Subteranean","Mines");
REPLACE into `IGUN`.`Flground` values(6,26,"Water","Torpedo");
REPLACE into `IGUN`.`Flground` values(7,27,"Water","Missile");
REPLACE into `IGUN`.`Flground` values(8,28,"Snow Vehicle","Machine Gun");
REPLACE into `IGUN`.`Flground` values(9,29,"Snow Vehicle","Laser");
REPLACE into `IGUN`.`Flground` values(10,30,"Walker","Laser Laser Pew Pew pew");
-- -----------------------------------------------------
-- Table `IGUN`.`Captain` Captainid,firstName,lastName,shipId
-- -----------------------------------------------------
REPLACE into `IGUN`.`Captain` values(1,"Ilvar","Casalis",1);
REPLACE into `IGUN`.`Captain` values(2,"Gilis","Talok",9);
REPLACE into `IGUN`.`Captain` values(3,"Mordora","Moroth",10);
REPLACE into `IGUN`.`Captain` values(4,"Erwel","Vetsor",7);
REPLACE into `IGUN`.`Captain` values(5,"Kunis","Hatake",8);
REPLACE into `IGUN`.`Captain` values(6,"Makise","Kurisu",5);
REPLACE into `IGUN`.`Captain` values(7,"Yuko","Suzuhana",3);
REPLACE into `IGUN`.`Captain` values(8,"Light","Yagami",6);
REPLACE into `IGUN`.`Captain` values(9,"Daiar-N",null,2);
REPLACE into `IGUN`.`Captain` values(10,"Shin","Machiya",4);
